id: AF819B0FC
title: Heart of Vajrasattva—The Heart of Confession, the King of Purification Practices,
  from 'The Immaculate Secret Vajrasattva'
type: translation
source_metadata:
  languages:
  - en
  - de
  - es
  - fr
  - it
  - nl
  - zh
  - bo
  datatype: PlainText
  created_at: 2022-03-01 06:33:17.671533
  last_modified_at: 2022-03-01 06:33:17.671536
