id: AF819B0FC
title: 'Cultivating the Pure Realm of Manifest Joy: A Guru Yoga of Vajrasattva'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 06:33:17.667866
  last_modified_at: 2022-03-01 06:33:17.667878
