id: AF819B0FC
title: 'The Cintāmaṇi (Wish-Fulfilling Jewel) Instruction: A Sādhana of the Glorious
  Vajrasattva, a Method of Purification and Accomplishment for Both Self and Others'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 06:33:17.673398
  last_modified_at: 2022-03-01 06:33:17.673401
