id: AF819B0FC
title: A Song of Innermost Praise to Vajrasattva
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 06:33:17.663222
  last_modified_at: 2022-03-01 06:33:17.663227
