id: AF819B0FC
title: Brief Vajrasattva Visualisation and Mantra Recitation
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 06:33:17.664607
  last_modified_at: 2022-03-01 06:33:17.664612
