id: AF819B0FC
title: A Method of Purifying Samaya Violations by Relying on the Glorious Guru Vajrasattva
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 06:33:17.657998
  last_modified_at: 2022-03-01 06:33:17.658004
