id: AF819B0FC
title: Concise Daily Practice of Vajrasattva
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 06:33:17.666515
  last_modified_at: 2022-03-01 06:33:17.666521
